### ISSUE TITLE
(Not an issue) Python version

### ISSUE THREAD

**Issue by Jaime02** [Bjordsvennson/NeuralNet#1]
Hi. First of all, sorry for opening an issue for saying this, but I have not found any other way of contact you. 

I have created a Python version of the neural network using your code. I am not patreon of Whats A Creel and I have not found his original GitHub, so I have written it looking at your repository. [Here it is](https://github.com/Jaime02/NeuralNet-Python )

Feel free to contact me if you want!

**Comment by Bjordsvennson** [comment]
Hey, I am also not a patreon of him so I just typed up what he had manually and tried to continue it with the resource he provided. I will point out that in this resource (http://neuralnetworksanddeeplearning.com/chap2.html), it provides python source code for back propagation and if I remember correctly, the entire neural net. I am fairly unfamiliar with how python works so I wasnt really able to make much use of that. Instead I just used the description of the algorithm. Maybe you'll have better luck than I did.

**Comment by Bjordsvennson** [comment]
I think it uses a slightly different structure as creel's given that its python, so I'm not sure if it's as simple as just pasting in the back propagation code, however haha

**Comment by Bjordsvennson** [comment]
I am almost positive that all the algorithms except for the back propagation work, (matrix operations, training set stuff)

**Comment by Bjordsvennson** [comment]
My biggest problem is lack of understanding of how the batching is supposed to work. At this point, I'm calculating deltas for the number of training samples equal to the number of columns in the layer, and adjusting the weights according to the average delta of each columns, so the average delta of the batch in other words.

**Comment by Bjordsvennson** [comment]
@Jaime02 realized this probably isnt notifying you lol here you go

**Comment by Jaime02** [comment]
First of all, I receive an email each time a comment is added but thanks for @ me 😄

I have had to adapt many things, the hardest one has been the file reading system. Is there any file writting system??
I feel like the net is uncomplete and there is some missing code... 

The python version could be improved significantly using NumPy, but now it is completely hand crafted.

I have a big problem which is that I don't know how to interpret the output 🤓

Another question, is there any cost function?

**Comment by Bjordsvennson** [comment]
You have to understand what it's being trained to do to understand the output. It's being trained to do the XOR operation because it was the simplest thing to implement to test it. The training samples have 2 inputs on one line, then the correct output of the XOR on the next. What the output of the program does, is it prints the input layer, which will be a batch of inputs, and the output layer will be a batch of outputs. By batch i just mean both matrices, so since there are two inputs to the XOR operation, there should be 2 rows printed with the number of columns being equal to the batch size. The outputs should be one output for each training batch meaning only one row for each training sample. Obviously you need to know how XOR works but it's really very simple. As for the cost function, I'm attempting to determine the cost in the backpropogation function itself. I do this by passing the targets into the wrapper function and conditionally processing then based on whether we are in the output layer or a hidden layer. I hope this makes more sense now.

**Comment by Bjordsvennson** [comment]
I admit it would be more clear if I delegated certain parts of the backprop process to different functions, but if you read the resource provided, the mathematical notation I comment each line with will make more sense as to what in attempting to do in the feedback function.

**Comment by Bjordsvennson** [comment]
And no there isnt any file writing because I didnt see it necessary. I completely agree its incomplete in the sense that it's not working. I wouldn't say there's "missing code" as much as the code that's there isnt logically functional. Once I can demonstrate that it will function correctly I can abstract things like passing a single input into the net and getting an output, but at that point I would probably adapt it to solving a more interesting problem before I did that.

**Comment by Bjordsvennson** [comment]
After all this is pretty much the product of a couple of days of work before I put it on the back burner, but I'll consider giving it a try again
